### ISSUE TITLE
Using with nested classes

### ISSUE THREAD

**Issue by legomushroom** [outpunk/postcss-modules#26]
With given styles of a component: 
```css
.handle {
  width:          20px; 
  height:         20px;
  border-radius:  50%;

  background:     cyan;
}
```

I would like to specify how the `.handle` component with live inside `.handle-parent` class:
```css
.handle-parent {
  // ..
  // some parent styles
  // ..

  .handle {
    position:    absolute;
    left:        50%;
  }

}
```
It doesn't work for me right now since `.handle` and `.handle-parent .handle` will obtain different `hashes`.
Any direction on how to solve the issue? Thanks!
