### ISSUE TITLE
How to use it with css files concat?

### ISSUE THREAD

**Issue by shoomyth** [outpunk/postcss-modules#28]
```css
/* button.css */
.button { background: grey; }

/* login-button.css */
.login-button {
  composes: button from "button.css";
  background: green;
}

/* logout-button.css */
.logout-button {
  composes: button from "button.css";
  background: red;
}
```

```js
return gulp.src('**/*.css')
    .pipe(gulpPostcss([
        postcssModules({
            getJSON: saveCssModulesJson
        })
    ]))
    .pipe(gulpConcat('bundle.css'))
```

```css
._button_aaa {
    background: grey;
}

._login-button_bbb {
    background: green;
}

._button_aaa {
    background: grey;
}

._logout-button_ccc {
    background: red;
}
```

```html
<button class="_login-button_bbb _button_aaa">Login</button>
<button class="_logout-button_ccc _button_aaa">Logout</button>
```

Logout button works as expected (red background). But login doesn't: second button selector (._button_aaa) overrides login-button (._login-button_bbb). And button has grey background.

Any suggestions?
